config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: 1.7.0_no_kubectl
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/inab/oeb_general_docs:
      branch: master
      repo: https://github.com/inab/oeb_general_docs
    github.com/inab/openEBench_vre:
      branch: master
      repo: https://github.com/inab/openEBench_vre
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/inab/openEBench_vre git:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-gold-millipede.sh
        container: qc.acc_freaky-blue-grasshopper
  QC.Doc:
    repos:
      github.com/inab/oeb_general_docs find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-grey-monkey.sh
        container: qc.doc_ready-magnolia-wolf
      github.com/inab/oeb_general_docs git:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-beige-bordeaux.sh
        container: qc.doc_craggy-celadon-pig
      github.com/inab/oeb_general_docs markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-mauve-moose.sh
        container: qc.doc_goopy-mauve-rattlesnake
      github.com/inab/oeb_general_docs restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-sepia-kiwi.sh
        container: qc.doc_shaky-brown-schnauzer
  QC.Lic:
    repos:
      github.com/inab/openEBench_vre licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-carmine-magpie.sh
        container: qc.lic_cheeky-peach-saola
  QC.Sec:
    repos:
      github.com/inab/openEBench_vre bandit:
        commands:
        - /usr/bin/env sh .sqa/script.beady-emerald-wolverine.sh
        container: qc.sec_bumpy-turquoise-eagle
  QC.Sty:
    repos:
      github.com/inab/openEBench_vre flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-orchid-lynx.sh
        container: qc.sty_snappy-cornflower-coati
  QC.Ver:
    repos:
      github.com/inab/openEBench_vre get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-red-drever.sh
        container: qc.ver_sleazy-chestnut-angelfish
timeout: 1800
